version: '3'
services:
  golang:
    build: .docker/development/golang
    command: /bin/sh -c "dep ensure && go run server.go"
    volumes:
      - .:/go/src/api
    ports:
      - 1323:1323
    stdin_open: true
    tty: true
